[tool.poetry]
name = "student-management-api"
version = "0.1.0"
description = "A FastAPI-based student management API."
authors = ["Sara Alila <sazalila39@yahoo.com>"]

[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.core.masonry.api"
