-- Create CUSTOMERS table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(45) NOT NULL,
    LAST_NAME VARCHAR(45) NOT NULL,
    ADDRESS VARCHAR(200),
    CITY VARCHAR(45),
    STATE VARCHAR(45),
    COUNTRY VARCHAR(45),
    ZIPCODE INT,
    PHONE_NUMBER VARCHAR(15),
    EMAIL_ID VARCHAR(100) UNIQUE NOT NULL
);

-- Create PAYMENTS table
CREATE TABLE PAYMENTS (
    PAYMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    PAYMENT_TYPE VARCHAR(45),
    EXPIRATION_DATE DATE,
    EMAIL_ID VARCHAR(100),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- Create PRODUCTS table
CREATE TABLE PRODUCTS (
    PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(200) NOT NULL,
    PRODUCT_TYPE VARCHAR(45),
    PRICE DECIMAL(10, 2)
);

-- Create ORDERS table
CREATE TABLE ORDERS (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    DEVICE VARCHAR(45),
    PRODUCT_ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    PAYMENT_ID INT NOT NULL,
    SHIPPING_ADDRESS VARCHAR(100),
    SHIPPING_CITY VARCHAR(100),
    SHIPPING_STATE CHAR(2),
    SHIPPING_COUNTRY VARCHAR(45),
    DELIVERED BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENTS(PAYMENT_ID)
);
